# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playboard',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
