# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playboard_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playboard',
            name='currstate',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
