# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20160917_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playboard',
            name='player1_id',
        ),
        migrations.RemoveField(
            model_name='playboard',
            name='player2_id',
        ),
        migrations.AddField(
            model_name='playboard',
            name='player1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playboard',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
