# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpooledtimestamp',
            old_name='user_id',
            new_name='user',
        ),
    ]
