# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0002_auto_20160917_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpooledtimestamp',
            name='pool_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpooledtimestamp',
            name='pool_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
