# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0003_auto_20160917_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpooledtimestamp',
            old_name='pool_time',
            new_name='pool_time_end',
        ),
        migrations.AddField(
            model_name='userpooledtimestamp',
            name='pool_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
