# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0004_auto_20160917_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpooledtimestamp',
            name='pool_time_end',
        ),
        migrations.RemoveField(
            model_name='userpooledtimestamp',
            name='pool_time_start',
        ),
        migrations.AlterField(
            model_name='userpooledtimestamp',
            name='pool_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
