# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=16)),
                ('collection_type', models.CharField(max_length=32)),
                ('owner_id', models.CharField(max_length=16)),
            ],
        ),
    ]
