# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0010_auto_20160917_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpooledtimestamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
