# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moveDevServer', '0011_auto_20160917_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpooledtimestamp',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
    ]
